# Configuration du serveur
server.port=3000

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Configuration de la base de données (MySQL depuis variables d'environnement)
spring.datasource.url=${MYSQL_URL:jdbc:mysql://mysql-3f9232cd-pewoparfait-02ce.b.aivencloud.com:21097/Banque?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${MYSQL_USER:avnadmin}
spring.datasource.password=${MYSQL_PASSWORD:password}
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Jackson (JSON date format)
spring.jackson.serialization.write-dates-as-timestamps=false
